// Port of PMETA (radar-core.js:3155-3552) — the Partner Network's full
// content is static authored reference copy (name/relationship/hub/
// coverage/score/why/value/tags/signals/actions per partner), not fetched
// or fabricated data; ported verbatim, unlike the fabricated-idea
// generators trimmed elsewhere in this migration.
export const PMETA = {
  aa: { name: 'American Airlines', code: 'AA', group: 'core', relationship: 'network partner', hub: 'Dallas / US network', coverage: 'North America feed', score: 96,
    why: 'Extends Qatar Airways reach across North America and strengthens premium transatlantic feed into Doha.',
    value: 'Useful for U.S. domestic feed, loyalty retention, and premium cabin demand.',
    tags: ['North America', 'Feed', 'Loyalty'],
    signals: ['North America connectivity into Doha can improve itinerary choice and conversion.', 'Joint loyalty earn/spend can reduce churn on high-value U.S. travellers.', 'Premium itineraries can be packaged more effectively through connected journeys.'],
    actions: ['Promote connect itineraries on Doha gateways with a premium-value message.', 'Use partner-led loyalty prompts to encourage Avios earn/spend.', 'Track direct-vs-partner conversion on key North America corridors.'] },
  ba: { name: 'British Airways', code: 'BA', group: 'core', relationship: 'network partner', hub: 'London / UK network', coverage: 'UK and Europe feed', score: 95,
    why: 'Strong UK and Europe coverage with premium overlap on long-haul and corporate travel.',
    value: 'Useful for premium flow, UK feed, and itinerary choice on Europe-Americas corridors.',
    tags: ['UK', 'Premium', 'Corporate'],
    signals: ['London connectivity can support higher-yield business and leisure itineraries.', 'Shared loyalty messaging can help defend frequent-flyer preference.', 'Competition-sensitive corridors may respond well to joint offers and bundles.'],
    actions: ['Surface joint premium itineraries on UK-origin search journeys.', 'Test loyalty-led campaigns on frequent flyer corridors.', 'Monitor direct booking share on transatlantic routes where the overlap is strongest.'] },
  qf: { name: 'Qantas', code: 'QF', group: 'core', relationship: 'network partner', hub: 'Australia', coverage: 'Australia and South Pacific feed', score: 92,
    why: 'Extends Qatar Airways reach into Australia and strengthens long-haul premium and leisure flows.',
    value: 'Useful for Australia connections, premium uplift, and loyalty-linked itinerary value.',
    tags: ['Australia', 'Long-haul', 'Premium'],
    signals: ['Australia itineraries can be sold as connected premium journeys through Doha.', 'Partner visibility can improve conversion where direct QR service is not the best fit.', 'Loyalty value can help defend high-value repeat travellers.'],
    actions: ['Promote partner-connected Australia journeys in executive and leisure search paths.', 'Track loyalty enrolment and repeat booking behaviour on Australia flows.', 'Use partner storylines in premium campaign creative.'] },
  cx: { name: 'Cathay Pacific', code: 'CX', group: 'core', relationship: 'network partner', hub: 'Hong Kong / Asia-Pacific', coverage: 'Asia-Pacific premium flow', score: 92,
    why: 'Strong Asia-Pacific reach with premium cabin relevance and high-value long-haul traffic.',
    value: 'Useful for premium Asian demand, high-value leisure, and business connectivity.',
    tags: ['Asia-Pacific', 'Premium', 'Business'],
    signals: ['Hong Kong connectivity can unlock premium Asia-Pacific itineraries.', 'Brand alignment supports business and premium leisure demand.', 'Joint loyalty framing can strengthen repeat travel on long-haul flows.'],
    actions: ['Surface connected premium journeys on Asia-Pacific origin markets.', 'Use loyalty messaging on repeat business and premium leisure routes.', 'Watch for route-shift or demand-softening signals that affect this corridor.'] },
  jl: { name: 'Japan Airlines', code: 'JL', group: 'core', relationship: 'network partner', hub: 'Japan', coverage: 'Japan and Northeast Asia feed', score: 90,
    why: 'Important for Japan-origin demand, premium business travel, and long-haul connecting itineraries.',
    value: 'Useful for premium Japan demand and itinerary depth into the Middle East and beyond.',
    tags: ['Japan', 'Premium', 'Business'],
    signals: ['Japan-origin customers often value schedule reliability and premium service depth.', 'Partner connections can improve conversion on long-haul business travel.', 'A strong network story helps position Qatar Airways for premium multi-leg itineraries.'],
    actions: ['Highlight partner-connected Japan itineraries in premium search flows.', 'Track loyalty engagement on repeat Japan business travel.', 'Use campaign creative that emphasises service consistency and reach.'] },
  ib: { name: 'Iberia', code: 'IB', group: 'core', relationship: 'network partner', hub: 'Madrid / Spain network', coverage: 'Spain and Europe feed', score: 90,
    why: 'Supports Spain and wider Europe connectivity with useful premium and leisure coverage.',
    value: 'Useful for Europe feed, leisure demand, and connected long-haul routes.',
    tags: ['Spain', 'Europe', 'Leisure'],
    signals: ['Spain-origin traffic can be shaped into connected premium and leisure journeys.', 'Partner-led coverage improves route choice across Europe and beyond.', 'Loyalty value can lift repeat booking and reduce channel leakage.'],
    actions: ['Promote Spain-origin connect itineraries in leisure-heavy markets.', 'Measure repeat booking and Avios engagement on shared flows.', 'Use partner messaging in seasonal campaigns for Europe demand.'] },
  ay: { name: 'Finnair', code: 'AY', group: 'core', relationship: 'network partner', hub: 'Helsinki / Nordic network', coverage: 'Nordic and Northern Europe feed', score: 88,
    why: 'Useful for Nordic connectivity and premium leisure/business journeys into Doha.',
    value: 'Useful for Europe coverage, premium Nordic demand, and connected itineraries.',
    tags: ['Nordics', 'Europe', 'Premium'],
    signals: ['Nordic connectivity can add useful feeder traffic into Qatar Airways long-haul network.', 'Premium customers often respond well to clear connection value and service consistency.', 'Strong partner coverage can reduce leakage to competing European hubs.'],
    actions: ['Promote Nordic connection value where Qatar Airways has strong long-haul coverage.', 'Use partner messaging around premium service and travel simplicity.', 'Track direct-booking conversion on Northern Europe itineraries.'] },
  mh: { name: 'Malaysia Airlines', code: 'MH', group: 'core', relationship: 'network partner', hub: 'Kuala Lumpur / Malaysia', coverage: 'South-East Asia feed', score: 88,
    why: 'Extends South-East Asia reach and supports leisure, family, and premium demand through Doha.',
    value: 'Useful for leisure, family travel, and connected long-haul itineraries.',
    tags: ['Asia', 'Leisure', 'Family'],
    signals: ['South-East Asia flows benefit from clear connectivity and itinerary breadth.', 'Family and leisure customers may value easier through-ticketing and baggage continuity.', 'Premium and leisure mix can support better campaign targeting.'],
    actions: ['Surface partner-connected itineraries for leisure and family booking journeys.', 'Track baggage and connection-related feedback on these flows.', 'Use seasonal campaigns to lift connected demand.'] },
  om: { name: 'Oman Air', code: 'WY', group: 'core', relationship: 'network partner', hub: 'Muscat / Oman', coverage: 'GCC and regional feed', score: 87,
    why: 'Regional partner that can strengthen GCC connectivity and business/leisure flow through Doha.',
    value: 'Useful for short-haul feed, regional frequency, and premium regional journeys.',
    tags: ['GCC', 'Regional', 'Feed'],
    signals: ['Regional connectivity is valuable for short-haul and multi-leg journeys.', 'GCC travellers often need simple connection paths and strong loyalty value.', 'The partner can help reduce direct leakage on regional corridors.'],
    actions: ['Highlight fast-connect regional journeys on GCC search paths.', 'Use loyalty prompts for repeat regional travellers.', 'Monitor regional corridor leakage and connection pain points.'] },
  rj: { name: 'Royal Jordanian', code: 'RJ', group: 'core', relationship: 'network partner', hub: 'Amman / Levant', coverage: 'Levant and wider regional feed', score: 86,
    why: 'Adds useful regional connectivity and supports business, VFR, and multi-stop itineraries.',
    value: 'Useful for Levant traffic, connected journeys, and loyalty retention.',
    tags: ['Levant', 'Regional', 'VFR'],
    signals: ['Regional and VFR traffic often benefits from simplified itinerary options.', 'Doha connectivity can improve choice for stopover and multi-leg travel.', 'Loyalty messaging may help defend repeat journeys.'],
    actions: ['Promote connected itinerary options for VFR and business travellers.', 'Highlight loyalty value on repeat regional trips.', 'Track partner-related conversion and repeat behaviour.'] },
  at: { name: 'Royal Air Maroc', code: 'AT', group: 'core', relationship: 'network partner', hub: 'Casablanca / Morocco', coverage: 'North and West Africa feed', score: 84,
    why: 'Extends Africa coverage and helps support long-haul itineraries into Doha from Africa and Europe.',
    value: 'Useful for Africa connectivity and extended long-haul feed.',
    tags: ['Africa', 'Feed', 'Connection'],
    signals: ['Africa-to-Doha connectivity can create attractive long-haul itineraries.', 'Leisure and VFR demand may value better network reach and scheduling.', 'Partner visibility can help convert traffic from nearby European and African markets.'],
    actions: ['Promote Africa-origin connection value in relevant markets.', 'Track conversion and connection satisfaction on Africa itineraries.', 'Use partner messaging in route and seasonal planning.'] },
  ul: { name: 'SriLankan Airlines', code: 'UL', group: 'core', relationship: 'network partner', hub: 'Colombo / Sri Lanka', coverage: 'South Asia and Indian Ocean feed', score: 84,
    why: 'Useful for South Asia and Indian Ocean flows, including leisure and VFR traffic.',
    value: 'Useful for VFR demand, family travel, and connected long-haul journeys.',
    tags: ['South Asia', 'VFR', 'Leisure'],
    signals: ['South Asia flows can benefit from more direct partner connectivity and loyalty value.', 'VFR and family travel often needs baggage and connection simplicity.', 'A stronger partner story can lift route resilience and repeat bookings.'],
    actions: ['Surface connected South Asia journeys in family and VFR booking journeys.', 'Track baggage/connection satisfaction on these itineraries.', 'Use loyalty-led prompts for repeat South Asia travel.'] },
  fj: { name: 'Fiji Airways', code: 'FJ', group: 'core', relationship: 'network partner', hub: 'Fiji / South Pacific', coverage: 'South Pacific leisure feed', score: 83,
    why: 'Extends South Pacific reach and supports long-haul leisure itineraries through Doha.',
    value: 'Useful for premium leisure and destination-led long-haul flow.',
    tags: ['South Pacific', 'Leisure', 'Long-haul'],
    signals: ['Leisure customers often need clear connection value and journey simplicity.', 'Long-haul itineraries can benefit from premium cabin positioning.', 'Partner messaging can help convert destination-led searches.'],
    actions: ['Promote connected leisure journeys for destination-led searches.', 'Highlight premium cabin value and journey simplicity.', 'Track leisure conversion and stopover interest on long-haul routes.'] },
  ha: { name: 'Hawaiian Airlines', code: 'HA', group: 'core', relationship: 'network partner', hub: 'Hawaii / US Pacific', coverage: 'Pacific leisure feed', score: 82,
    why: 'Supports Pacific leisure flows and can improve route coverage for destination-led travel.',
    value: 'Useful for leisure demand, premium itinerary mix, and route coverage.',
    tags: ['Pacific', 'Leisure', 'Destination'],
    signals: ['Destination-led travel benefits from clear connection and service value.', 'Premium leisure travelers may respond well to a strong network story.', 'Partner feed can support itinerary depth without adding owned capacity.'],
    actions: ['Highlight destination-led connected journeys in leisure search.', 'Promote premium leisure and stopover value where relevant.', 'Measure partner-assisted conversion on Pacific itineraries.'] },
  as: { name: 'Alaska Airlines', code: 'AS', group: 'core', relationship: 'network partner', hub: 'Seattle / US West Coast', coverage: 'US West Coast feed', score: 82,
    why: 'Useful for West Coast feed and North America connectivity into Doha.',
    value: 'Useful for U.S. West Coast demand and connected long-haul itineraries.',
    tags: ['West Coast', 'Feed', 'North America'],
    signals: ['West Coast feed can support strong long-haul network coverage.', 'Connected journeys can improve itinerary choice for business and leisure travellers.', 'Loyalty value is especially useful on repeat North America travel.'],
    actions: ['Promote West Coast connect itineraries in long-haul search journeys.', 'Use loyalty cues to encourage repeat booking.', 'Track conversion and connection satisfaction on North America corridors.'] },
  ei: { name: 'Aer Lingus', code: 'EI', group: 'growth', relationship: 'strategic growth partner', hub: 'Dublin / Ireland', coverage: 'Ireland and transatlantic reach', score: 86,
    why: 'A useful growth partner for Ireland-origin traffic and transatlantic itineraries.',
    value: 'Useful for selective corridor growth, loyalty, and connected premium flow.',
    tags: ['Ireland', 'Growth', 'Transatlantic'],
    signals: ['Ireland-origin itineraries may respond well to clear connection and loyalty value.', 'Transatlantic flows can be monetised through connected premium journeys.', 'Partner awareness can improve route choice and reduce leakage.'],
    actions: ['Promote Ireland-linked connected itineraries in relevant searches.', 'Track premium and loyalty response on transatlantic flows.', 'Use campaign hooks to lift partner-assisted conversions.'] },
  va: { name: 'Virgin Australia', code: 'VA', group: 'growth', relationship: 'strategic growth partner', hub: 'Australia', coverage: 'Australia feed', score: 86,
    why: 'A strong growth partner for Australia-origin itineraries and high-value leisure travel.',
    value: 'Useful for Australia route growth, premium leisure, and loyalty-led journeys.',
    tags: ['Australia', 'Growth', 'Leisure'],
    signals: ['Australia demand can benefit from a clearer partner story and itinerary value.', 'Premium leisure and family travellers may value more flexible connection choices.', 'Joint loyalty messaging can lift repeat engagement.'],
    actions: ['Promote partner-connected Australia itineraries in leisure and premium search.', 'Track loyalty uptake and repeat booking on Australia flows.', 'Use seasonal campaigns for family and premium leisure segments.'] },
  mf: { name: 'Xiamen Airlines', code: 'MF', group: 'growth', relationship: 'strategic growth partner', hub: 'Xiamen / China network', coverage: 'China feed', score: 84,
    why: 'Useful for China connectivity and the ability to extend reach into multiple domestic markets.',
    value: 'Useful for China-origin traffic, connection depth, and loyalty value.',
    tags: ['China', 'Growth', 'Feed'],
    signals: ['China connectivity can be important for route depth and broader network reach.', 'Partner-led itineraries can improve conversion where direct service is limited.', 'A visible partner story helps defend high-value China flows.'],
    actions: ['Promote partner-connected China itineraries in relevant markets.', 'Monitor partner-assisted conversion and loyalty behaviour.', 'Use the partner story in market-facing route and campaign planning.'] },
}

export function partnerEntriesByGroup(group) {
  return Object.entries(PMETA).filter(([, meta]) => (meta.group || 'core') === group)
}
